name: quickstart
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-edge.d89ae3c2c6bacedb385c1c2f40bcfb6aa178663b <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.0
  build_web_compilers: ^4.0.0
  lints: ^2.0.0
